CREATE TABLE USERS(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(512),
	PWD VARCHAR(512),
	NAME VARCHAR(512),
	DISPLAYNAME VARCHAR(512),
	GOOGLE_ID VARCHAR(512),
	FACEBOOK_ID VARCHAR(512),
    KAKAO_ID VARCHAR(512),
    NAVER_ID VARCHAR(512)
)ENGINE=INNODB;

INSERT INTO USERS (EMAIL, PWD, NAME, DISPLAYNAME) VALUES ('bonwook.koo@patterntech.co.kr', '1111', '구본욱', 'Bonwook');

DROP TABLE USERS;